sudo: required

language: generic

services:
  - docker

before_install:
  - mkdir -p ~/ruster/src
  - echo -e "[package]\nname = \"hello_ruster\"\nversion = \"0.1.0\"\nauthors = [\"Ruster <ruster@example.com>\"]" > ~/ruster/Cargo.toml
  - echo "fn main() { println!(\"Hello from ruster!\") }" > ~/ruster/src/main.rs
  - docker build -t yamafaktory/ruster .

script:
  - docker run --rm -it -v ~/ruster:/ruster yamafaktory/ruster cargo run
